/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 JACK_black.glb --transform 
Files: JACK_black.glb [68.8MB] > C:\xampp\htdocs\varsitybase\src\assets\models\JACK_black-transformed.glb [964.26KB] (99%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/JACK_black-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.model.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/JACK_black-transformed.glb')
